defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.15.3

version: 2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint:js
      - run: npm run test
      - run: npm run build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'b0:b1:14:bd:b1:83:74:54:5f:8e:fa:9f:7f:35:68:d4'
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: ~/repo/.circleci/publish-and-tagging.sh
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
